config/routes.rb
Rails.application.routes.draw do

get '/' => 'static#index'
get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/signup' => 'dancers#new'
delete '/logout' => 'sessions#destroy'

get '/auth/:provider/callback' => 'sessions#create'

  resources :dancers
  resources :categories, only: [:new, :index, :create]
  resources :comments
  resources :dance_classes do
    resources :comments, only: [:new, :index]  
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :dance_classes
  

    scope :filter_duplicates, -> { group(:name).having("count(*) >= 1")}

    def self.order_by_size
        order(dance_classes: :desc)
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :dancer
  belongs_to :dance_class

  validates :title, presence: true
  validates :content, presence: true

  validates :dance_class, uniqueness: { scope: :dancer, message: "Only 1 comment per user" }


end

app/models/dance_class.rb
class DanceClass < ApplicationRecord
  self.inheritance_column = nil

  belongs_to :category
  belongs_to :dancer
  has_many :comments
  has_many :dancers, through: :comments

  validates :type, presence: true
  validates :description, presence: true
  validate :already_exists

  scope :order_by_comments, -> { left_joins(:comments).group(:id).order("size desc")}



  def self.by_dancer(dancer_id)
    where(dancer: dancer_id)
  end

  def already_exists
    dance_class = DanceClass.find_by(type: type, category_id: category_id)
    if !!dance_class && dance_class != self
    errors.add(:type, 'has already been added for that category')
    end
  end

  def type_category
    "#{type} - #{category.name}"
   end


   def category_attributes=(hash)
     category = Category.find_or_create_by(name: hash[:name])
     #push it into dance_class
     self.category = category
   end


end

app/models/dancer.rb
class Dancer < ApplicationRecord
    has_many :comments 
    has_many :dance_classes, through: :comments
    has_many :dance_classes
    
    validates :username, uniqueness: true, presence: true, length: { minimum: 5}   
    validates :email, uniqueness: true, presence: true
    validates :password, length: { in: 6..100 }

    has_secure_password 
    has_one_attached :image



  def self.create_by_google_omniauth(auth)
    self.find_or_create_by(email: auth[:info][:email]) do |u|
      u.username = auth["info"]["name"]
      u.password = SecureRandom.hex
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_dancer, :logged_in?, :create_session

    private

    def require_login
        redirect_to login_path unless session[:dancer_id]
    end

    def logged_in?
        session[:dancer_id] ? true : false
    end

    def current_dancer
         session[:dancer_id]
    end

    def create_session
        session[:dancer_id] = @dancer.id
      end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    
  before_action :require_login


  def index
    @categories = Category.filter_duplicates
    @dance_classes = DanceClass.all
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :require_login
    before_action :set_comment, only: [:edit, :show]

    def new
        if @dance_class = DanceClass.find_by_id(params[:dance_class_id])
            @comment = @dance_class.comments.build
          else
            @comment = Comment.new
          end
    end

    def create
        @comment = Comment.new(comments_params)
        @comment.dancer_id = session[:dancer_id]
        if @comment.save
            redirect_to dance_classes_path
        else
            render :new
        end 
    end 
      
    def show
    end 

    def edit
    end 
    
    def index
    #how to I check if its nested & a valid id
        if @dance_class = DanceClass.find_by_id(params[:dance_class_id])
    #then its nested
            @comments = @dance_class.comments
        else
    #if its not nested
            @comments = Comment.all
        end 
    end

    private
    
    def comments_params
        params.require(:comment).permit(:dance_class_id, :title, :content)
    end

    def set_comment
        @comment = Comment.find_by(id: params[:id])
    end

end

app/controllers/dance_classes_controller.rb
class DanceClassesController < ApplicationController
    before_action :require_login
    before_action :set_dance_class, only:[:show, :edit, :update, :destroy]
   
    def index
      @dance_classes = DanceClass.all
    
    end 


    def new 
      @dance_class = DanceClass.new
      @dance_class.build_category     
    end 

    def create 
        @dance_class = DanceClass.new(dance_class_params)
        @dance_class.dancer_id = session[:dancer_id]    
      if @dance_class.save              
         redirect_to dance_class_path(@dance_class)
      else 
         render :new
      end
    end 

    def show
      @comments = @dance_class.comments
    end
  
    def edit
      if session[:dancer_id] != @dance_class.dancer_id
        redirect_to dancer_path(session[:dancer_id])
      end 
    end
  
    def update
      if @dance_class.update(dance_class_params)
        redirect_to dance_classes_path
      else
        render :edit
      end
    end

    def destroy 
      if current_dancer != @dance_class.dancer_id
          redirect_to dancer_path(session[:dancer_id])
      else 
          @dance_class.destroy
          redirect_to dance_classes_path
      end
  end

    private
      
    def dance_class_params
        params.require(:dance_class).permit(:type, :description, category_attributes: [:name]) 
    end

    def set_dance_class
        @dance_class = DanceClass.find_by(id: params[:id])
    end
end

app/controllers/dancers_controller.rb
class DancersController < ApplicationController

    def new
        @dancer = Dancer.new

    end 

    def index
        @dancers = Dancer.all
    end

    def create
        @dancer = Dancer.new(dancer_params)      
        if @dancer.save                           
            create_session
            redirect_to dancer_path(@dancer)
        else 
            render :new
        end
    end

    def show 
        @dancer = Dancer.find_by(id: params[:id])    
    end

    private 

    def dancer_params
        params.require(:dancer).permit(:username, :email, :password)   
    end 

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @dancer = Dancer.new 
  end 

  def create
    if params[:provider] == 'google_oauth2'
      @dancer = Dancer.create_by_google_omniauth(auth)
      create_session
      redirect_to dancer_path(@dancer)

    else 
     #try to find dancer in the database
     @dancer = Dancer.find_by(username: params[:dancer][:username])

    
     #did we find someone & did they put in the right pw
      if @dancer && @dancer.authenticate(params[:dancer][:password])
      create_session
      redirect_to dancer_path(@dancer)
      else
        flash[:error] = "Sorry, log info was incorrect. Please try again."
         redirect_to login_path
      end 
    end
  end 


    def destroy
      session.delete(:dancer_id)
      flash[:notice] = "You have successfully logged out."
      redirect_to '/' 
    end 

    def omniauth
        @dancer = Dancer.create_by_google_omniauth(auth)
      if @dancer
        create_session
        redirect_to dancer_path(@dancer)
      else 
        redirect_to login_path
      end 
    end 
    
    private
    
    def auth
        request.env['omniauth.auth']
    end
    
    
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def index  
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper


end

app/helpers/dance_classes_helper.rb
module DanceClassesHelper
end

app/helpers/dancers_helper.rb
module DancersHelper

    def check_image(dancer)
        image_tag (dancer.image), size: "100x80" unless dancer.image.attachment == nil 
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/categories/index.html.erb
<section id="cover" class="min-vh-100">
<div id="cover-caption">
    <div class="container">
        <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form h5-4">
            <div class="px-2 ">
                <div class="blk_center row card-deck border-info mb-3"> 
                    <h1>Categories</h1>
                        <hr>
                            <% @categories.each do |c| %>
                             <div class="blk_center">
                           <h4 style="color: purple;"><b><%= c.name %></b></h4>
                           <h6>Classes:<% @dance_classes.each do |w| %></h6>
                                   <% if w.category_id == c.id %>
                                   <em><p class="text-white"><%= w.type %></em></p>
                                   <% end %>
                                <% end %>
                            </div>
                            <hr>
                            <% end %>

<%= render 'dance_classes/style' %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |c|%>
    <% if params[:dance_class_id] %>
    <%= c.hidden_field :dance_class_id %>

  <% else %>
    <div>
      <%= c.label :dance_class_id, "Select a Dance Class" %>
      <%= c.collection_select :dance_class_id, DanceClass.all, :id, :type_category, include_blank: true %>
    </div>
  <% end %>
  
  <br>
  <div>
    <%= c.label :title %>
    <br>
    <%= c.text_field :title %>
  </div>
  <br>
  <div>
    <%= c.label :content %>
    <br>
    <%= c.text_area :content, size: "50x10" %>
  </div>
  <br>

  <%= c.hidden_field :dance_class_id %>


  <%= c.submit %>
  

<% end %>

app/views/comments/index.html.erb
<section id="cover" class="min-vh-100">
    <div id="cover-caption">
        <div class="container">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                <h1 class="text-dark">All comments for <br><%= @dance_class.type %> Dance Class</h1>

                    <h5 class="text-dark">Hosted By: <%= @dance_class.dancer.username %></h>
                        <div class="px-2 blk_center row card-deck border-light mb-3">

                        <% @comments.each do |c| %>
                        <h4 class="text-primary"><%= check_image(c.dancer) %><%=c.dancer.username %> posted: </h4>
                        <p style="color: purple;"><em><%= c.content %></em><p>
                        <p class="text-dark"> Created-at <%= c.created_at %></p>
                        <hr>
                       
                        <% end %>
                        <%= link_to  "Add a Comment", new_dance_class_comment_path(@dance_class) %>
                    </div>
                </div>
            
        </div>
    </div> 
</section>

<%= render 'dance_classes/style' %>

app/views/comments/new.html.erb
  
<section id="cover" class="min-vh-100">
<div id="cover-caption">
    <div class="container">
            <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                <h1 class="display-4 py-2 text-truncate text-dark">Add a comment</h1>
                    <div class="px-2">

                      <%= render partial: 'layouts/errors', locals: {obj: @comment} %>
                      <%= render 'form' %>
                      <%= link_to  "Cancel", dance_classes_path %>
                      </div>
            </div>
        
    </div>
</div> 
</section>


<%= render 'dance_classes/style' %>

app/views/comments/show.html.erb
<h1>Your comment</h1>


<%= @comment.title %>
<br>
<%= @comment.content %>

app/views/dance_classes/_form.html.erb
<h4>Select a Category</h4>
<%= form_for(@dance_class) do |f| %>
<div>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
</div>
<br>
  <p>OR Add A New Category:</p>
  <div>
      <%= f.fields_for :category do |m| %>
          <%= m.text_field :name %>
      <datalist id="category_name">
          <% Category.all.each do |c| %>
         <option value = "<%= c.name %>"  ></option>
          <% end %>
      </datalist>
      <br>
      <% end %>
  </div>
<br>
<br>

  <div>
      <h5><%= f.label :type, value="Class Name"%></h5>
      <%= f.text_field :type %>
  </div>
<br>
  <div>
      <h5><%= f.label :description %></h5>
      <%= f.text_area :description %>
  </div>

<br>


  <br>
      <%= f. submit %>
<% end %>

app/views/dance_classes/_style.html.erb
<style>
 #cover {
    background: #c8a2c8 center center no-repeat;
    background-size: cover;
    height: 100%;
    text-align: center;
    display: flex;
    align-items: center;
    position: relative;
}

#cover-caption {
    width: 100%;
    position: relative;
    z-index: 1;
}

form:before {
    content: '';
    height: 100%;
    left: 0;
    position: absolute;
    top: 0;
    width: 100%;
    background-color: rgba(0,0,0,0.2);
    z-index: -1;
    border-radius: 10px;
}

.blk_center {

    display:inline-block;    
    width: 100%;
    background-color: #FFFFFF;
    z-index: -1;
    border-radius: 5px;
    
}

</style>

app/views/dance_classes/edit.html.erb
<section id="cover" class="min-vh-100">
    <div id="cover-caption">
        <div class="container">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form h5-4">
                        <div class="px-2 ">
                          <br>
            <div class="blk_center row card-deck border-info mb-3">  


<h1>Edit Dance Class</h1>



<%= render partial: 'form'%>
<%= render 'style' %>

app/views/dance_classes/index.html.erb
<section id="cover" class="min-vh-100">
    <div id="cover-caption">
        <div class="container">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form h5-4">
                        <div class="px-2 ">
                          <br>
                          <div class="blk_center row card-deck border-info mb-3">  

                            <h3>All Dance Classes</h3>
                          </div>
                          <hr>
                            <% @dance_classes.each do |w| %>
                            <div class="blk_center row card-deck border-info mb-3">
                            
                            <h5>Category: <br><em><%= w.category.name %></em>
                            <h5>Class Name: <br><em><%= w.type %></h5></em>
                            <p><strong>Description:</strong><br><em><%= w.description %></em> </p>
                            <h6>Hosted By: <%= w.dancer.username %></h6>
                            <%= check_image(w.dancer) %>
                            <h6>Comments: <%= w.comments.count %>  </h6>
                            
                            
                            <%= link_to "More Details", dance_class_path(w.id) %>
                            <br>
                            <%= link_to "Edit Dance Class", edit_dance_class_path(w.id) if w.dancer_id == session[:dancer_id] %>
                            <br>
                            <%= link_to "Delete Dance Class", dance_class_path(w), :confirm => "Are you sure?", :method => :delete if w.dancer_id == session[:dancer_id] %>
                            <br>
                            <%= link_to "Add A Comment", new_dance_class_comment_path(w.id) %>
                            </div>
                            <hr>
                            <% end %>
                        

                </div>
              
                
                
        </div> 
      </div>
</section>
<%= render 'style' %>

app/views/dance_classes/new.html.erb
<%= render partial: 'layouts/errors', locals: {obj: @dance_class} %>

<section id="cover" class="min-vh-100">
    <div id="cover-caption">
        <div class="container">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                    <h4 class="display-4 py-2 text-dark">Add A Dance Class</h4>
                        <div class="px-2">
                        
                        <%= render 'form' %>
                        <%= link_to  "Cancel", dancer_path(session[:dancer_id]) %>

                
                    </div>
                </div>
            
        </div>
    </div> 
</section>

<%= render 'style' %>

app/views/dance_classes/show.html.erb
<section id="cover" class="min-vh-100">
    <div id="cover-caption">
        <div class="container">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">

                        <h1>Dance Class Details</h1>
                        <div class="blk_center row card-deck border-info text-dark mb-3">

                            <h3><%= @dance_class.type %></h3>
                            <p>Description: <br> <em><%= @dance_class.description %><em> </p>
                      
                            </div>
                            <br>
                            <div class="blk_center row card-deck border-primary mb-3 text-dark">

                            <% @comments.all.each do |c| %>
                                <%= check_image(c.dancer) %> 
                                <h5 <%= c.dancer.username.capitalize %> posted</h5>
                                <h6>Subject: <div style="color: purple;">"<%= c.title %>"</h6>
                                <h6>Comment: <div style="color: purple;">"<%= c.content %>"</h5>
                                <p> Created at: <%= c.created_at %></p>
                                <hr>
                                <% end %> 
                                <%= link_to  "View Comments", dance_class_comments_path(@dance_class) %>
                            </div>
            
                            </div>
            
                            </div>
                        </div> 
                    </section>
<%= render 'style' %>

app/views/dancers/_dance_classes.html.erb
<% @dancer.dance_classes.each do |w| %>
    <div class="blk_center text-dark">
        <h4>Category: <%= w.category.name %><br></h4>
        <h4>Class Name: <%= w.type %><br></h4>
        <h5>Description: <%= w.description %></h5>
        <h6>Comments: <%= w.comments.count %>  </h6>

    <%= link_to "More Details", dance_class_path(w.id) %>
    <br>
    <%= link_to "Edit Dance Class", edit_dance_class_path(w.id) if w.dancer_id == session[:dancer_id] %>
    <br>
    <%= link_to "Delete Dance Class", dance_class_path(w), :confirm => "Are you sure?", :method => :delete if w.dancer_id == session[:dancer_id] %>
    <br>
    <%= link_to "Add A Comment", new_dance_class_comment_path(w.id) %>
    </div>
        <hr>
<% end %>

app/views/dancers/_form.html.erb
<%= render partial: 'layouts/errors', locals: {obj: @dancer} %>
<br>

<%= form_for(@dancer) do |f|%>
  <div>
  <%= f.label :username %>
  <%= f.text_field :username %> 
  </div>
 
  <div>
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>

<div>
  <%= f.label :password %>
  <%= f.password_field :password %> 
  </div>
  <br>
 
  <%= f.submit "Sign Up", class: "btn-dark" %>
  </div>
<% end %>

app/views/dancers/index.html.erb
<section id="cover" class="min-vh-100">
    <div id="cover-caption">
        <div class="container">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                    <%= image_tag("Logo.png", size: "200x200") %> 
                    <div class="px-2">
<br>

                            <% @dancers.each do |d| %>
                            <div class="blk_center row card-deck border-info mb-3">
                            <h3><%= check_image(d)%> Dancer: <br><div style="color: purple;"><%= d.username %></h3>
                            <p>Created on - <%= d.created_at %><p>
                            </div>
                            
                            <% end %>



                </div>
            </div>
        </div>
    </div>
</section>

    <%= render 'dance_classes/style' %>

app/views/dancers/new.html.erb
<section id="cover" class="min-vh-100">
    <div id="cover-caption">
        <div class="container">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                <%= image_tag("Logo.png", size: "200x200") %> 

                    <h1 class="display-4 py-2 text-truncate text-light">Sign Up</h1>
                    <div class="px-2">

                      <%= render 'form' %>

                      </div>
        </div>
    </div>
    </div>
</section>
<%= render 'dance_classes/style' %>

app/views/dancers/show.html.erb
  
<section id="cover" class="min-vh-100">
<div id="cover-caption">
    <div class="container">
            <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                <%= image_tag("Logo.png", size: "200x200") %> 
                <div class="px-2">

                    <h1>Welcome <div style="color: purple;"><%= @dancer.username %></div></h1>
                    
                    <%= check_image(@dancer) %> 


                        <h1>Your Dance Classes</h1>
                     
                        
                        <%= render 'dance_classes' %>

            </div>
        </div>
    </div>
</div>
</section>


<%= render 'dance_classes/style' %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(obj.errors.count, "error") %> prohibited this from being saved:</h2>
 
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li style="color: red;"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
          
        <li class="nav-item">
        <a class="nav-link" <%= link_to  "Profile", dancer_path(session[:dancer_id]) %> </a>
      </li>
      <li class="nav-item">
         <a class="nav-link" <%= link_to  "All Dance Classes", dance_classes_path %> </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to  "Create A Dance Class", new_dance_class_path %> </a>
      </li>
      
      <li class="nav-item">
         <a class="nav-link" <%= link_to  "All Categories", categories_path %> </a>
      </li>
      <li class="nav-item">
            <a class="nav-link" <%= link_to  "All Dancers", dancers_path %> </a>
          </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to  "Log Out", logout_path, method: :delete %> </a>
      </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VirtualDanceMachine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag "https://code.jquery.com/jquery-3.5.1.slim.min.js" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"  %>
    <%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" %>

   

    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
  </head>


  <body>
  <header>
  <nav class="navbar navbar-expand-lg navbar-light bg-white shadow">
    <div class="container">
      <a class="navbar-brand" href="/"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home
                  <span class="sr-only">(current)</span>
                </a>
          </li>
         
  
  
      <% if logged_in? %>
  
          <%= render 'layouts/nav' %>
          
      <% end %>
      
        </ul>
      </div>
    </div>
  
  </nav>
  </header>
  
      <%= yield %>
   

    </body>
  </html>